spring.application.name=digital-expenses-mcp
spring.main.web-application-type=none

# NOTE: You must disable the banner and the console logging
# to allow the STDIO transport to work !!!
spring.main.banner-mode=off
logging.pattern.console=

spring.ai.mcp.server.name=digital-expenses-mcp
spring.ai.mcp.server.version=0.0.1

logging.file.name=./mox/digital-expenses-mcp/target/digital-expenses-mcp.log

auth.pazzword=password
auth.clientId=expensesclientadmin
auth.userName=expensesuser
auth.grantType=password
auth.tokenEndpoint= http://localhost:8080/realms/expenses/protocol/openid-connect/token


expenses.tokenEndpoint=http://localhost:8084/open/api/v1/expenses/

