spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/realms/expenses
  kafka:
    producer:
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    bootstrap-servers: localhost:9092
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: digital-onboarding-userprofile
  datasource:
    password: ecommerceapp
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/full-stack-ecommerce?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
jwt:
  auth:
    converter:
      principle-attribute: expensesuser #TODO JWT change
      resource-id: expensesclientadmin #TODO JWT change
management:
  endpoint:
    health:
      show-details: always
server:
  port: '8081'