spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/realms/expenses
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
  kafka:
    consumer:
      group-id: kafka-demo-group1
      auto-offset-reset: earliest #it shall read all messages from the beginning set latest if need to ignore the previous messages
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    bootstrap-servers: localhost:9092
  redis:
    host: localhost
    port: '6379'
  application:
    name: digital-transactions-expenses
  datasource:
    password: ecommerceapp
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/full-stack-ecommerce?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC



jwt:
  auth:
    converter:
      principle-attribute: expensesuser #TODO JWT change
      resource-id: expensesclientadmin #TODO JWT change
  credts:
    clientId: expensesclientadmin #TODO JWT change
    password: password #TODO JWT change
    username: expensesuser #TODO JWT change
    url: http://localhost:8080/realms/expenses/protocol/openid-connect/token #TODO JWT change

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
  health:
    circuitbreakers:
      enabled: true
server:
  port: '8084'

userprofile:
  service:
    url: http://localhost:8081/api/user/


resilience4j:
  circuitbreaker:
    instances:
      userprofileService:
        sliding-window-type: COUNT_BASED
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        register-health-indicator: true
        ignoreExceptions:
            - com.digital.transactions.expenses.exception.UserNotFoundException


